## _config.yml
```yaml
# Site settings
title: "Blog Başlığınız"
description: "Blog açıklamanız buraya gelecek"
baseurl: "" # alt dizin kullanıyorsanız, örn: /blog
url: "https://kullaniciadi.github.io" # kullaniciadi kısmını değiştirin

# Yazar bilgileri
author:
  name: "Adınız Soyadınız"
  email: "email@example.com"
  bio: "Kısa biyografiniz"
  twitter_username: kullaniciadiniz
  github_username:  kullaniciadiniz
  linkedin_username: kullaniciadiniz

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Sosyal medya
twitter:
  username: kullaniciadiniz
  card: summary

# Google Analytics
google_analytics: # UA-XXXXXXXX-X

# SEO
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
```
